language: scala

jdk: openjdk8

env:
  global:
    # GITHUB_OAUTH_TOKEN (for GitHub user scala-jenkins, same token as scabot)
    secure: "JpmPbk0jBrYfeJopnd8PVXKekofEdTMB4jDll8N10WrYiaSEpMcWIBXPG8dYTq3jjC2kYk2DVIzqDCppchr4KcUq0Mu8sigv0LrWcMGRHo1vHB9Od3h+dFuTkjfY9+6dD7rTmLTs4ABCiLT9DxeiryRu1NaUIJfkJLoVi0O0+RQ="

script:
  - source scripts/common
  - if [[ "$scala_sha" != "" ]]; then postCommitStatus "pending"; fi
  - scripts/jobs/release/smoketest

after_script:
  - |
    if [[ "$scala_sha" != "" ]]; then
      if [[ "$TRAVIS_TEST_RESULT" == "0" ]]; then
        local state="success"
      else
        local state="failure"
      fi
      postCommitStatus $state
    fi

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
